//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameHeader
    {
        public System.Guid GameId { get; set; }
        public string PlayerId { get; set; }
        public string Player2Id { get; set; }
        public int PlayerPoints { get; set; }
        public int PlayerRoundsWins { get; set; }
        public int Player2Points { get; set; }
        public int Player2RoundsWins { get; set; }
        public int RoundsCount { get; set; }
        public Nullable<System.Guid> GameRoundId { get; set; }
    
        public virtual GameRound GameRound { get; set; }
    }
}
