//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameRound
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GameRound()
        {
            this.GameHeaders = new HashSet<GameHeader>();
        }
    
        public System.Guid GameRoundId { get; set; }
        public string AvailableCards { get; set; }
        public string PlayerCards { get; set; }
        public string PlayerLifeCards { get; set; }
        public string Player2Cards { get; set; }
        public string Player2LifeCards { get; set; }
        public string PlayerTurnId { get; set; }
        public string CardPits { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GameHeader> GameHeaders { get; set; }
    }
}
