//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameHeader
    {
        public System.Guid GameId { get; set; }
        public string PlayerId { get; set; }
        public string Player2Id { get; set; }
        public int PlayerPoints { get; set; }
        public int PlayerRoundsWins { get; set; }
        public int Player2Points { get; set; }
        public int Player2RoundsWins { get; set; }
        public int RoundsCount { get; set; }
        public System.Guid ActualRoundId { get; set; }
    
        public virtual GameRound GameRound { get; set; }
    }
}
