//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GameHeader()
        {
            this.PlayerName = "";
            this.PlayerPhoto = "";
            this.Player2Name = "";
            this.Player2Photo = "";
        }
    
        public System.Guid GameId { get; set; }
        public string PlayerId { get; set; }
        public string Player2Id { get; set; }
        public int PlayerPoints { get; set; }
        public int PlayerRoundsWins { get; set; }
        public int Player2Points { get; set; }
        public int Player2RoundsWins { get; set; }
        public int RoundsCount { get; set; }
        public Nullable<System.Guid> GameRoundId { get; set; }
        public string PlayerName { get; set; }
        public string PlayerPhoto { get; set; }
        public string Player2Name { get; set; }
        public string Player2Photo { get; set; }
    
        public virtual GameRound GameRound { get; set; }
    }
}
